### ISSUE TITLE
This UDPBD-Server does not work with OPL 2044 UDPBD, it only works with OPL 1973 UDPBD

### ISSUE THREAD

**Issue by 10522** [israpps/udpbd-server#1]
@israpps, @parrado, @rickgaiser, @awaken1ng, please compile a new version of UDPBD-Server for Windows from [this](https://gitlab.com/ps2max/udpbd-server) code.

**Comment by 10522** [comment]
@israpps, you have released a version for Linux. Can you please release the version for Windows?

**Comment by israpps** [comment]
> @israpps, you have released a version for Linux. Can you please release the version for Windows?

I was never able to compile the windows one myself
My compilers don't seem to have all the needed headers to define all the ioctl crap and other stuff
